### ISSUE TITLE
feat(database)!: send diagnostics to Log Analytics workspace

### ISSUE THREAD

**Issue by hknutsen** [equinor/terraform-azurerm-sql#61]

**Comment by hknutsen** [comment]
Look into if this is necessary when we have an auditing policy setup at the server scope: https://github.com/equinor/terraform-azurerm-sql/blob/main/main.tf#L91-L97

**Comment by kov117** [comment]
I believe the auditing policy should resolve the issue but i am not 100 % sure, some more research would help to confirm but so far my research seems to suggest yes.

Ref.
- https://stackoverflow.com/questions/69444804/not-able-to-enable-sql-auditing-and-sending-the-logs-to-a-pvt-endpoint-enabled-s
This link is from someone who was not able to enable SQL Auditing and sending the logs to a Pvt Endpoint enabled Storage Account, but then the code used to resolve the issue is the same code that is being used on this SQL

- https://learn.microsoft.com/en-us/sql/relational-databases/security/auditing/sql-server-audit-database-engine?view=sql-server-ver16
This link goes in details of auditing on an SQL server and specifics on database

- https://learn.microsoft.com/en-us/windows/security/threat-protection/auditing/planning-and-deploying-advanced-security-audit-policies#bkmk-2
This link goes into details of how to plan and deploy advanced security audit policies
